Algoritmo "era-para_ser-um_relogio"


Var
 hora : inteiro


Inicio
  escreval (" coloque a hora")
leia (hora)

 se (hora >= 00) e (hora <= 5) entao
escreval (" boa madrugada")

senao
se (hora >= 6) e (hora <= 12) entao
  escreval (" bom dia")
  
senao
 se (hora >= 13)  e (hora <= 18) entao
escreval(" boa tarde")

senao
se (hora >= 19) entao
escreval (" boa noite")

fimse
fimse
fimse
fimse


.


Fimalgoritmo